### ISSUE TITLE
[Bug] Some sent messages stick to the bottom

### ISSUE THREAD

**Issue by Huy-Ngo** [vector-im/element-android#2494]
## Describe the bug
When I send a message, it may happen that a sent message stick to the bottom of the conversation, hiding away the new messages. There is another copy of the message placed at the correct point in timeline as well.

This sticking message cannot be deleted. This is not observed in other clients.

## To Reproduce

I am not sure how to reproduce this bug. It might be caused by weak and unstable internet connection and/or exiting the app too quick, since that was the case for both encounters.

## Expected behavior
There should be only one copy of the message and it should be placed at the correct point in timeline.

## Screenshots
![image](https://user-images.githubusercontent.com/19296926/101244499-7a553480-3739-11eb-88c5-896e0aa53a1d.png)

As can be seen from the screenshot, The messages from Nov 17 and Dec 4 (yesterday) are sticking at the bottom, while newer messages are above it. Before yesterday, the only message that had been sticking is the message from Nov 17.

![image](https://user-images.githubusercontent.com/19296926/101244692-7d045980-373a-11eb-8258-954ea103d4a3.png)

Holding the sticking message shows no options for deleting.

(Censored messages are not mine or are confidential.)

## Smartphone
 - Device: Redmi Note 7 Pro
 - OS: Android 10
 - MIUI version: 12.0.1 Stable

## Additional context
 - App version and store: 1.0.10 - Play Store
 - Homeserver: matrix.org

**Comment by djsmiley2k** [comment]
I have the same issue. It occurred for me when the internet cutout. 

1.0.10 [40100102] (G-b652) is my version. I'm on a separate homeserver.

**Comment by djsmiley2k** [comment]
![Screenshot_20201205-184847~2](https://user-images.githubusercontent.com/462892/101260921-2d6a6180-372b-11eb-960b-578c42d21182.png)

This was sent, as it shows, a number of days ago. I wonder if some meta data on the post about the time stamp is missing causing it to always be the 'latest'. However I can't find any way to get the debug info for this.

**Comment by SierraKiloBravo** [comment]
+1, I am also experiencing this. This happened before (a few weeks ago), and both occurances of this issue were in rooms bridged by https://github.com/Half-Shot/matrix-appservice-discord. I am unsure if the issue is caused by the AS or by riot itself.

Clearing cache and FC'ing does not fix the issue. Could also be due to the fact that the message is not old enough (the message that is pinned to the bottom is from November 30th).

I am using the latest version of Synapse as of writing (I updated from the Matrix Debian repos to exclude that as being the cause)

**Comment by bjonnh** [comment]
For me clearing the cache solves temporarily the issue, but another message get stuck soon after anyway…

**Comment by bjonnh** [comment]
It happens with the default matrix/vector servers and on normal rooms as well as IRC bridged rooms.

**Comment by bjonnh** [comment]
Also duplicate of #2358   … I have been plagued by months with this issue.

**Comment by Krzmbrzl** [comment]
I have found a workaround: https://github.com/vector-im/element-android/issues/2358#issuecomment-758174968

**Comment by Huy-Ngo** [comment]
A recent update apparently has resolved this and remove the sticking messages

**Comment by tjaderxyz** [comment]
This is still happening for me.

**Comment by SimonBrandner** [comment]
@tjaderxyz I am not sure, but the fix might still in the beta version. So try waiting and probably clear your cache, but from what I've heard this should be fixed

**Comment by tjaderxyz** [comment]
I'm on 1.0.12 from fdroid, which is the most recent version there. When can
I expect the fixed release to be there?

Em qua, 27 de jan de 2021 11:44, Šimon Brandner <notifications@github.com>
escreveu:

**Comment by SimonBrandner** [comment]
@tjaderxyz I am on 1.0.14 which I believe is the newest version from Play Store. I don't know when this will get on F-Droid, sorry

**Comment by penn5** [comment]
Still happens on 1.1.0. It just happened in a group I only created this morning. I am sending a rageshake.

**Comment by Huy-Ngo** [comment]
I'm on 1.0.17 and the messages disappeared for me, but since you're still experiencing it I assume they're not removed due to the bug being fixed but because the app being overwritten by F-droid (I previously used Google Play version, which was suspended).

**Comment by ncm** [comment]
I still see it in 1.1.0. Some older ones seem to be gone, but there are new ones.

**Comment by bmarty** [comment]
See #516
