### ISSUE TITLE
Viewing Jitsi participant crashes the app

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#5745]
Probably since Jitsi 5.0.2, incuded in Element 1.4.10

- Start a Jitsi call and join the conf
- Click on the three dot menu and on "Participants"

The app crashes.

On our side you can maybe disable this menu entry, but I guess the issue has to be fixed on the Jitsi library.

Stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.facebook.react.uimanager.FabricViewStateManager.hasStateWrapper()' on a null object reference
        at com.facebook.react.views.textinput.ReactEditText.updateCachedSpannable(ReactEditText.java:981)
        at com.facebook.react.views.textinput.ReactEditText.access$300(ReactEditText.java:75)
        at com.facebook.react.views.textinput.ReactEditText$TextWatcherDelegator.onTextChanged(ReactEditText.java:1092)
        at android.widget.TextView.sendOnTextChanged(TextView.java:11631)
```

**Comment by bmarty** [comment]
Should be fixed in the coming Jitsi SDK, see https://github.com/jitsi/jitsi-meet/issues/11375#issuecomment-1141401472

**Comment by rajil** [comment]
Same goes for Speaker Stats. Turning that on during an active call causes Element to crash.

**Comment by bmarty** [comment]
I confirm that going to Speaker stats does not crash the app anymore.

**Comment by rajil** [comment]
@bmarty  Clicking on Participants in Jitsi call still crashes Element version 1.4.31
